name: Python Application

on:
  schedule:
    - cron: "0 0 1,15 * *"
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run Python script
        run: python main.py

      - name: Deploy to GitHub Pages
        run: |
          git fetch
          git checkout gh-pages
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add patches.json
          git commit -m "Update patches JSON"
          git push origin gh-pages
